name: CI/CD Pipeline for Tests

on:
  push:
    branches:
      - main
      - ci-pipeline
      - testes-automatizados
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Cypress
      run: npx cypress install

    - name: Install Allure Reporter
      run: npm install allure-commandline mocha-allure-reporter --save-dev

    - name: Run Cypress tests (E2E)
      run: npx cypress run --reporter mocha-allure-reporter

    - name: Install Maestro CLI
      run: curl -Ls "https://get.maestro.mobile.dev" | bash

    - name: Run Maestro tests
      run: npx maestro test ./maestro/login_fluxo.yaml --format junit --output maestro-report/report.xml
    - name: Generate Allure Report
      run: |
        mkdir -p allure-results
        cp maestro-report/report.xml allure-results/
        npx allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
