name: CI/CD Pipeline for testes-outsera

on:
  push:
    branches:
      - main
      - ci-pipeline
      - testes-automatizados
      - maestro
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Reinstalar dependências para a plataforma
        run: |
          rm -rf node_modules
          npm install

      - name: Instalar Cypress e Plugin Allure
        run: |
          npx cypress install
          npm install @shelex/cypress-allure-plugin allure-commandline --save-dev

      - name: Configurar Plugin Allure
        run: |
          mkdir -p cypress/plugins
          echo "module.exports = {" >> cypress/plugins/index.js
          echo "  setupNodeEvents(on, config) {" >> cypress/plugins/index.js
          echo "    require('@shelex/cypress-allure-plugin/writer')(on);" >> cypress/plugins/index.js
          echo "    return config;" >> cypress/plugins/index.js
          echo "  }," >> cypress/plugins/index.js
          echo "};" >> cypress/plugins/index.js

      - name: Executar testes da API IBGE
        run: |
          TEST_TYPE=api npx cypress run --spec "cypress/e2e/api-tests/ibge-api.cy.js"

      - name: Gerar Relatório Allure
        run: |
          mkdir -p allure-results
          npx allure generate allure-results --clean -o allure-report

      - name: Fazer upload do Relatório Allure
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Instalar CLI do Maestro
        run: npm install -g maestro@2.1.1

      - name: Executar teste do Maestro
        run: |
          mkdir -p maestro-report
          npx maestro test maestro/app-release.apk --format junit --output maestro-report.xml || echo "Erro na execução do teste do Maestro"

      - name: Fazer upload do Relatório do Maestro
        if: success()
        run: |
          if [ -f maestro-report.xml ]; then
            echo "Relatório encontrado, iniciando upload"
            mv maestro-report.xml maestro-report/
          else
            echo "Relatório não encontrado, não será feito upload"
          fi

      - name: Instalar Preprocessador Cucumber
        run: npm install @badeball/cypress-cucumber-preprocessor --save-dev

      - name: Instalar dependências adicionais
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libgtk-3-0 xvfb

      - name: Executar testes E2E (Cucumber)
        run: |
          xvfb-run -a bash -c 'TEST_TYPE=e2e npx cypress run --spec "cypress/e2e/**/*.feature" --env allure=true'

      - name: Gerar Relatório Allure para Testes E2E
        run: |
          mkdir -p allure-results
          npx allure generate allure-results --clean -o allure-e2e-report

      - name: Fazer upload do Relatório Allure para Testes E2E
        uses: actions/upload-artifact@v4
        with:
          name: allure-e2e-report
          path: allure-e2e-report

      - name: Instalar K6
        run: |
          sudo apt-get update
          curl -s https://packagecloud.io/install/repositories/loadimpact/k6/script.deb.sh | sudo bash
          sudo apt-get install -y k6

      - name: Executar teste de carga com K6
        run: |
          k6 run load-tests/load-test.js

      - name: Fazer upload do Relatório de Teste de Carga
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: load-tests/load-test.json
